[package]
name = "logictree"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
dashmap = { version = "6.1.0", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive", "rc"] }
