[package]
name = "logictree"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
papaya = "0.2.3"
serde = { version = "1.0.219", features = ["derive", "rc"] }
